M48
; DRILL file {KiCad 8.0.6} date 2025-12-06T11:12:11+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-06T11:12:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X68.15Y-85.8
X68.15Y-148.6
X220.15Y-85.8
X220.15Y-148.6
M30
